name = "auth-worker"
main = "src/auth-worker.js"
compatibility_date = "2023-05-18"

# Cloudflare Pages configuration
pages_build_output_dir = "dist"

[vars]
# Add your environment variables here

[[d1_databases]]
binding = "DB"
database_name = "auth-database"
database_id = "6eb5face-d932-4aa7-8c92-45b69fce008a"
